---
title: "Create shock01 analysis file"
output:   
  html_document:
    fig_height: 5
    fig_width: 5
bibliography: Implan Paper.bib
csl: apa.csl
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(readr)
library(stargazer)
library(ggformula)
library(tidyverse)
library(matsindf)
library(matsbyname)
library(statnet)
library(igraph)
library(qgraph)
library(expss)
library(sjmisc)
library(sjlabelled)
library(scales)
library(ggthemes)


data   <- file.path("Data")

```


```{bash, include=FALSE}
# Aggregate the Top Ten Industries by Employment

# This program cuts out the TopTen Industry information from the Overview files.
# The aggregated spreadsheet is then used to categorize each county as mfg or svc. 
# See google sheet.

## ON WINDOWS: must go to shell and run "dos2windows Create*" before running 
## the script below

./CreateAggTopTenIndustryFile.sh

```


```{bash, include=FALSE}
# Aggregate the IO files and the Results output

./CreateAggIOFile.sh
./CreateAggResultsFile.sh
```


```{r readfiles, include=FALSE}
## Read in the IO matrices 

filename="AggIOall2014.csv"
fileNamewithPath <- file.path(data,filename)

IOall <- as_tibble(read_csv(fileNamewithPath)) %>% 
  rename(s01=s1,s02=s2,s03=s3,                                            
         s04=s4,s05=s5,s06=s6,                                                        
         s07=s7,s08=s8,s09=s9) %>%
                  mutate_all(~replace(., is.na(.), 0)) %>% 
                  select(-desc)   

```


```{r IO metrics, include=FALSE}
## Create the IO Metrics as needed.

IO.df <- IOall %>%
            mutate(rownames=dplyr::recode(sector,`0`="TotIndOut",
                                        `1`="s01",`2`="s02",`3`="s03",
                                        `4`="s04",`5`="s05",
                                        `6`="s06",`7`="s07",`8`="s08",
                                        `9`="s09",`10`="s10",`11`="s11")) %>%
            select(-sector) %>%
  
          gather(key="colnames",value="vals",-county,-rownames,-year,factor_key = TRUE) %>%
          mutate(matrix="IO",rowtypes="sector",coltypes="sector") %>%
          mutate(matrix=case_when(rownames=="TotIndOut" ~ "g",TRUE ~ "IO")) %>%
          group_by(county,year,matrix) %>%
  
          collapse_to_matrices(matnames="matrix",matvals="vals") %>% 
  
          spread(key="matrix",value="vals") %>%

   mutate(A = matrixproduct_byname(IO,hatinv_byname(g)),
          L = invert_byname(Iminus_byname(A)),
          Y = matrixproduct_byname(invert_byname(L),transpose_byname(g)),
          Bona_cent=rowsums_byname(L),
          B_mean=unaryapply_byname(mean,Bona_cent) %>% as.numeric(),
          B_sd=unaryapply_byname(sd,Bona_cent) %>% as.numeric())


```



```{r IO, include=FALSE}
## Read in the Simulation Results and Create Variables for Analysis

filename="AggResults2014.csv"
fileNamewithPath <- file.path(data,filename)

shock01 <- as_tibble(read_csv(fileNamewithPath)) %>%
            mutate(sector=dplyr::recode(sector,`0`="Total",`1`="s01",`20`="s02",`41`="s03",
                                        `52`="s04",`65`="s05",
                                        `395`="s06",`396`="s07",`408`="s08",
                                        `417`="s09",`472`="s10",`520`="s11")) %>%
            select(-description) %>%
            filter(sector=="Total") %>%
            select(-sector)


shock01 <- inner_join(shock01,IO.df) %>% 
  mutate(county=dplyr::recode(county,`St Clair`="St. Clair", `St Joseph`="St. Joseph"))
```

```{r getvars, include=FALSE}
filename="IMPLAN Industry Type 2014.csv"
fileNamewithPath <- file.path(data,filename)
vars <-as_tibble(read_csv(fileNamewithPath))
shock01 <- inner_join(shock01,vars)

filename="IMPLANVars2014.csv"
fileNamewithPath <- file.path(data,filename)
vars <-as_tibble(read_csv(fileNamewithPath))
shock01 <- inner_join(shock01,vars)

filename="NonIMPLANVars.csv"
fileNamewithPath <- file.path(data,filename)
vars <-as_tibble(read_csv(fileNamewithPath))
shock01 <- inner_join(shock01,vars)

shock01 <- shock01 %>% mutate(pctindirect = indirect/direct,
                 pctinduced = induced/direct,
                 GRP = grp/1000000000) 

var_lab(shock01$IndustryType)="Primary Industry"

shock01$IndustryTypebyOutput <- set_labels(
  shock01$IndustryTypebyOutput,
  labels = c(`M` = "Manufacturing", `S` = "Service")
)

dollar_format(shock01$GRP)

```
